# fly.toml app configuration file generated for storybooker on 2025-09-13T00:51:51-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'storybooker'
primary_region = 'yyz'

[build]
  builder = "paketobuildpacks/builder:base"
  buildpack = ["paketo-buildpacks/python"]
[build.args]
  BP_CPYTHON_VERSION = "3.11.4"

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1